export async function openFallingDamage() {
  const DialogV2 = foundry?.applications?.api?.DialogV2;
  if (!DialogV2) return ui.notifications.error("Этот инструмент требует DialogV2.");
  const FLAG_SCOPE="world", FLAG_KEY="gurpsFallDamageMacro";
  const PRESETS={
    prone:{label:"Человек — плашмя",optionLabel:"Плашмя (60)",terminal:60},
    normal:{label:"Человек — обычное падение",optionLabel:"Обычное падение (80)",terminal:80},
    streamlined:{label:"Человек — ногами или головой вниз",optionLabel:"Вертикально (100)",terminal:100},
    dense:{label:"Плотный или обтекаемый предмет",optionLabel:"Плотный предмет (200)",terminal:200}
  };
  const valid=new Set([...Object.keys(PRESETS),"custom"]);
  const num=v=>Number(String(v??"").trim().replace(",","."));
  const bool=v=>v===true||v==="true"||v==="on"||v===1||v==="1";
  const defaults={gravity:.138,pressure:1.3,height:19,hp:10,fallType:"normal",customTerminal:120,hardSurface:true};
  const saved=game.user.getFlag(FLAG_SCOPE,FLAG_KEY)??{};
  const oldTerminal=num(saved.terminalEarth);
  let migrated=defaults.fallType;
  if(Number.isFinite(oldTerminal)&&oldTerminal>0){const found=Object.entries(PRESETS).find(([,p])=>Math.abs(p.terminal-oldTerminal)<.001);migrated=found?found[0]:"custom";}
  const previous={
    gravity:saved.gravity??defaults.gravity,pressure:saved.pressure??defaults.pressure,height:saved.height??defaults.height,hp:saved.hp??defaults.hp,
    fallType:valid.has(saved.fallType)?saved.fallType:migrated,
    customTerminal:(Number.isFinite(num(saved.customTerminal))&&num(saved.customTerminal)>0)?num(saved.customTerminal):(Number.isFinite(oldTerminal)&&oldTerminal>0?oldTerminal:defaults.customTerminal),
    hardSurface:saved.hardSurface===undefined?defaults.hardSurface:bool(saved.hardSurface)
  };
  const options=Object.entries(PRESETS).map(([k,p])=>`<option value="${k}" ${previous.fallType===k?"selected":""}>${p.optionLabel}</option>`).join("");
  const data=await DialogV2.input({window:{title:"Расчёт урона от падения"},position:{width:640},content:`<style>.oq-fall{max-height:70vh;overflow-y:auto;padding:0 9px 0 2px;font-size:.88em}.oq-fall-row{display:grid;grid-template-columns:minmax(190px,1fr) minmax(250px,280px);align-items:center;gap:8px 12px;padding:10px 3px;border-bottom:1px solid rgba(128,128,128,.25)}.oq-fall-row:first-child{border-top:1px solid rgba(128,128,128,.25)}.oq-fall-row[hidden]{display:none!important}.oq-fall-row label,.oq-fall-label{font-weight:700}.oq-fall-row input,.oq-fall-row select{width:100%;margin:0}.oq-fall-hint{grid-column:1/-1;margin:0;opacity:.78;font-size:.86em}.oq-surface{display:grid;grid-template-columns:1fr 1fr;border:1px solid rgba(128,128,128,.3);border-radius:4px;overflow:hidden}.oq-surface input{position:absolute;opacity:0;pointer-events:none}.oq-surface label{display:flex;justify-content:center;align-items:center;gap:5px;min-height:34px;margin:0;cursor:pointer;opacity:.65}.oq-surface input:checked+label{opacity:1;box-shadow:inset 0 0 0 1px var(--color-border-highlight,#ff6400);background:rgba(255,255,255,.1)}@media(max-width:600px){.oq-fall-row{grid-template-columns:1fr}.oq-fall-hint{grid-column:1}}</style><div class="oq-fall">
    <div class="oq-fall-row"><label>Гравитация, G</label><input type="number" name="gravity" value="${previous.gravity}" min="0" step="any"></div>
    <div class="oq-fall-row"><label>Атмосферное давление, атм.</label><input type="number" name="pressure" value="${previous.pressure}" min="0" step="any"><p class="oq-fall-hint">0 считается вакуумом: конечная скорость не ограничена.</p></div>
    <div class="oq-fall-row"><label>Высота падения, ярды</label><input type="number" name="height" value="${previous.height}" min="0" step="any" autofocus></div>
    <div class="oq-fall-row"><label>ЕЖ падающего объекта</label><input type="number" name="hp" value="${previous.hp}" min=".01" step="any"></div>
    <div class="oq-fall-row"><label>Тип падения</label><select name="fallType">${options}<option value="custom" ${previous.fallType==="custom"?"selected":""}>Своё значение</option></select><p class="oq-fall-hint" id="oq-terminal-preview"></p></div>
    <div class="oq-fall-row oq-custom" ${previous.fallType==="custom"?"":"hidden"}><label>Своя земная конечная скорость, ярдов/с</label><input type="number" name="customTerminal" value="${previous.customTerminal}" min=".01" step="any"></div>
    <div class="oq-fall-row"><span class="oq-fall-label">Поверхность столкновения</span><div class="oq-surface"><input id="oq-hard" type="radio" name="hardSurface" value="true" ${previous.hardSurface?"checked":""}><label for="oq-hard"><i class="fa-solid fa-hammer"></i>Твёрдая</label><input id="oq-soft" type="radio" name="hardSurface" value="false" ${previous.hardSurface?"":"checked"}><label for="oq-soft"><i class="fa-solid fa-water"></i>Мягкая</label></div><p class="oq-fall-hint">При столкновении с твёрдым объектом ЕЖ для расчёта удваиваются.</p></div>
  </div>`,ok:{label:"Рассчитать",icon:"fa-solid fa-calculator"},rejectClose:false,modal:true,render:(_e,d)=>{const r=d.element;const sel=r.querySelector('select[name="fallType"]'),row=r.querySelector('.oq-custom'),inp=r.querySelector('input[name="customTerminal"]'),prev=r.querySelector('#oq-terminal-preview');if(!sel||!row||!inp||!prev)return;const update=()=>{const k=sel.value;row.hidden=k!=="custom";if(k==="custom"){const x=num(inp.value);prev.textContent=Number.isFinite(x)&&x>0?`Будет использована земная конечная скорость ${x} ярдов/с.`:"Введите земную конечную скорость.";}else prev.textContent=`Макрос автоматически использует ${PRESETS[k]?.terminal??"—"} ярдов/с.`;};sel.addEventListener("change",update);inp.addEventListener("input",update);update();}});
  if(!data)return; const v=data.object??data; const gravity=num(v.gravity),pressure=num(v.pressure),height=num(v.height),hp=num(v.hp),fallType=String(v.fallType??""),customTerminal=num(v.customTerminal??previous.customTerminal),hardSurface=bool(v.hardSurface); const preset=PRESETS[fallType],terminalEarth=fallType==="custom"?customTerminal:preset?.terminal;
  const errors=[]; if(!Number.isFinite(gravity)||gravity<0)errors.push("гравитация должна быть числом не меньше 0");if(!Number.isFinite(pressure)||pressure<0)errors.push("давление должно быть числом не меньше 0");if(!Number.isFinite(height)||height<0)errors.push("высота должна быть числом не меньше 0");if(!Number.isFinite(hp)||hp<=0)errors.push("ЕЖ должны быть больше 0");if(!valid.has(fallType))errors.push("не выбран допустимый тип падения");if(!Number.isFinite(terminalEarth)||terminalEarth<=0)errors.push("земная конечная скорость должна быть больше 0");if(errors.length)return ui.notifications.error(`Ошибка ввода: ${errors.join("; ")}.`);
  try{await game.user.setFlag(FLAG_SCOPE,FLAG_KEY,{gravity,pressure,height,hp,fallType,customTerminal,hardSurface,terminalEarth});}catch(e){console.warn(e)}
  const freeFallSpeed=Math.sqrt(21.4*gravity*height); const terminalSpeed=pressure===0?Infinity:terminalEarth*Math.sqrt(gravity)/Math.sqrt(pressure); const impactSpeed=Math.min(freeFallSpeed,terminalSpeed); const limited=Number.isFinite(terminalSpeed)&&freeFallSpeed>terminalSpeed; const effectiveHp=hardSurface?hp*2:hp; const rawDice=effectiveHp*impactSpeed/100;
  const damage=value=>{if(value<=0)return"0";if(value<1){if(value<=.25)return"1к−3";if(value<=.5)return"1к−2";return"1к−1";}return`${Math.floor(value+.5+Number.EPSILON)}к`;};
  const fmt=(x,d=2)=>Number.isFinite(x)?new Intl.NumberFormat("ru-RU",{maximumFractionDigits:d}).format(x):"не ограничена";
  const rows=[['Гравитация',`${fmt(gravity,3)}G`],['Давление',`${fmt(pressure,3)} атм.`],['Тип падения',fallType==="custom"?"Своё значение":preset.label],['Земная конечная скорость',`${fmt(terminalEarth)} ярда/с`],['Скорость без атмосферы',`${fmt(freeFallSpeed)} ярда/с`],['Местная конечная скорость',pressure===0?"не ограничена — вакуум":`${fmt(terminalSpeed)} ярда/с`],['Ограничение скорости',limited?"Да — скорость ограничена атмосферой":"Нет — конечная скорость не достигнута"],['Скорость столкновения',`<strong>${fmt(impactSpeed)} ярда/с</strong>`],['Поверхность',hardSurface?"твёрдая — ЕЖ удвоены":"мягкая — ЕЖ не удвоены"],['ЕЖ для расчёта',fmt(effectiveHp)],['Кубики до округления',`${fmt(rawDice,3)}к`]].map(([a,b],i)=>`<tr${i<10?' style="border-bottom:1px solid rgba(128,128,128,.22)"':''}><th style="width:55%;padding:3px 5px;text-align:left">${a}</th><td style="padding:3px 5px">${b}</td></tr>`).join('');
  await ChatMessage.create({speaker:ChatMessage.getSpeaker({alias:"Расчёт падения"}),content:`<div style="font-size:.78em;line-height:1.2"><h3 style="margin:0 0 5px;font-size:1.15em">Падение с ${fmt(height)} ярдов</h3><table style="width:100%;margin:0;font-size:.96em;border-collapse:collapse"><tbody>${rows}</tbody></table><hr style="margin:5px 0"><p style="margin:3px 0 0;font-size:1.2em"><strong>Урон: ${damage(rawDice)} дробящего</strong></p></div>`});
}
