export async function openReactionRoll() {
  const DialogV2 = foundry?.applications?.api?.DialogV2;
  if (!DialogV2) return ui.notifications.error("Этот инструмент требует DialogV2.");
  const FLAG_SCOPE="world", FLAG_KEY="gurpsReactionRoll";
  const esc=v=>foundry?.utils?.escapeHTML?foundry.utils.escapeHTML(String(v??"")):String(v??"");
  const parseIntOr=(v,f=0)=>{const t=String(v??"").trim().replace(",", ".");if(!t)return f;const n=Number(t);return Number.isInteger(n)?n:Number.NaN;};
  const signed=n=>n>=0?`+${n}`:String(n);
  const R=[
    {min:-Infinity,max:0,range:"0 или меньше",name:"Ужасная",en:"Disastrous",general:"НИП ненавидят персонажей и будут действовать, чтобы всячески им навредить.",combat:"НИП будут яростно атаковать, не прося и не давая пощады.",business:"Коммерческие сделки обречены на провал. Торговец откажется иметь с персонажами дело.",help:"Просьбы о помощи полностью отклоняются; ситуация может перерасти во враждебную.",information:"Просьбы об информации вызывают гнев; возможна немедленная враждебная реакция.",loyalty:"НИП ненавидит вас или связан с вашими врагами и использует удобный шанс, чтобы предать вас."},
    {min:1,max:3,range:"1–3",name:"Очень плохая",en:"Very Bad",general:"НИП не нравятся персонажи и он будет действовать им во вред, если это окажется удобным.",combat:"НИП атакуют и сбегут только если поймут, что у них нет шансов.",business:"Торговец просит втрое больше справедливой цены или предлагает треть справедливой цены.",help:"Просьбы о помощи встречают отказ; повторная реакция не может быть лучше нейтральной.",information:"НИП умышленно лжёт.",loyalty:"НИП не любит персонажей и покинет службу или предаст их при первой возможности."},
    {min:4,max:6,range:"4–6",name:"Плохая",en:"Bad",general:"НИП не заботят персонажи и станет действовать против них, если это выгодно.",combat:"НИП атакуют, если персонажи не превосходят их числом; иначе могут отступить и вернуться позже.",business:"Торговец просит двойную цену или предлагает половину справедливой цены.",help:"Просьбы о помощи встречают отказ.",information:"НИП откажется, солжёт или потребует денег; после оплаты информация может быть правдивой, но неполной.",loyalty:"НИП вас не уважает и может оставить или предать вас при умеренной выгоде."},
    {min:7,max:9,range:"7–9",name:"Слабая",en:"Poor",general:"НИП не впечатлён. Он может стать враждебным, если это выгодно или неопасно.",combat:"НИП угрожают или оскорбляют и требуют уйти; при отказе могут атаковать, если не уступают числом.",business:"Торговец запросит 120% справедливой цены или предложит 75%.",help:"Просьбы встречают отказ, но взятки, уговоры или угрозы могут сработать; возможен новый бросок с -2.",information:"НИП заявит, что не знает, или даст неполные сведения; взятка может улучшить результат.",loyalty:"НИП не впечатлён вами или работой и может уйти либо предать при достаточной выгоде."},
    {min:10,max:12,range:"10–12",name:"Нейтральная",en:"Neutral",general:"НИП игнорирует персонажей насколько это возможно. Он совершенно не заинтересован.",combat:"НИП идёт своей дорогой и позволяет персонажам сделать то же; если бой уже идёт, пытается отступить.",business:"Сделки проходят по справедливым ценам.",help:"Простые просьбы поддерживаются, сложные встречают отказ; можно попробовать ещё раз с -2.",information:"Простая информация предоставляется, сложный вопрос получает поверхностный ответ.",loyalty:"НИП работает достаточно усердно, чтобы начальник был доволен, но не более того."},
    {min:13,max:15,range:"13–15",name:"Хорошая",en:"Good",general:"НИП симпатизирует персонажам и готов помочь в разумных, будничных рамках.",combat:"НИП считает персонажей приятными людьми или слишком грозными соперниками; помощь или информация получают +1 к следующему броску реакции.",business:"Сделки проходят хорошо; торговец использует справедливые цены и может дать полезную информацию.",help:"Разумные просьбы поддерживаются; при отказе НИП всё равно даст полезный совет.",information:"На вопрос ответят честно.",loyalty:"НИП нравитесь вы и/или работа; он лоялен и согласится на разумный риск."},
    {min:16,max:18,range:"16–18",name:"Очень хорошая",en:"Very Good",general:"НИП высокого мнения о персонажах и будет полезен и дружелюбен.",combat:"НИП настроены дружелюбно; просьбы о помощи или информации получают +3 к реакции; уже начавшийся бой постараются прекратить.",business:"Торговец согласится на очень выгодные для персонажей условия в пределах разумного и предложит помощь и совет.",help:"Просьбы поддерживаются, если они не совсем неразумны; полезная информация предоставляется бесплатно.",information:"НИП ответит подробно и выдаст связанную информацию.",loyalty:"НИП будет работать очень упорно и, если нужно, станет рисковать жизнью."},
    {min:19,max:Infinity,range:"19 или больше",name:"Отличная",en:"Excellent",general:"НИП дико восхищён персонажами и будет действовать им во благо, пока позволяют способности.",combat:"НИП очень дружественны и могут временно присоединиться к партии; просьбы о помощи или информации получают +5.",business:"Сделки будут очень выгодны, торговец предложит помощь и совет.",help:"НИП сделают всё, что в их силах, и могут предложить дополнительную помощь.",information:"Будет получен полный ответ; НИП может приложить усилия, чтобы добыть недостающие сведения.",loyalty:"НИП предан вам или вашему делу, ставит ваши интересы выше своих и может даже умереть за вас."}
  ];
  const saved=game.user.getFlag(FLAG_SCOPE,FLAG_KEY); const prior=Number.isInteger(Number(saved?.modifier))?Number(saved.modifier):null;
  const data=await DialogV2.input({window:{title:"Таблица реакций"},position:{width:520},content:`<style>.oq-react{font-size:.94em}.oq-react-row{display:grid;grid-template-columns:1fr 150px;align-items:center;gap:10px 14px;padding:10px 2px;border-top:1px solid rgba(128,128,128,.28);border-bottom:1px solid rgba(128,128,128,.28)}.oq-react-row input{width:100%;margin:0}.oq-react-row label{font-weight:700}.oq-react .hint{opacity:.78;font-size:.9em}</style><div class="standard-form oq-react"><div class="oq-react-row"><label>Модификатор реакции</label><input type="number" name="modifier" value="${prior===null?"":prior}" placeholder="+0" step="1" autofocus></div><p class="hint">Бросок: 3к6 + модификатор. Введённое значение сохраняется между запусками.</p></div>`,ok:{label:"Бросить",icon:"fa-solid fa-dice"},rejectClose:false,modal:true});
  if(!data)return; const v=data.object??data; const mod=parseIntOr(v.modifier,0); if(!Number.isInteger(mod)) return ui.notifications.error("Модификатор должен быть целым числом.");
  try{await game.user.setFlag(FLAG_SCOPE,FLAG_KEY,{modifier:mod});}catch(e){console.warn(e)}
  const roll=await new Roll("3d6").evaluate(); const dice=Number(roll.total), total=dice+mod; const reaction=R.find(x=>total>=x.min&&total<=x.max)??R.at(-1);
  const row=(t,x)=>`<div style="margin-bottom:8px"><strong>${esc(t)}</strong><br>${esc(x)}</div>`;
  await ChatMessage.create({speaker:ChatMessage.getSpeaker(),rolls:[roll],content:`<div style="font-size:.94em;line-height:1.35"><h3 style="margin:0 0 7px">Таблица реакций</h3><div style="margin-bottom:8px">3к6: <strong>${dice}</strong> · Модификатор: <strong>${signed(mod)}</strong> · Итог: <strong>${total}</strong></div><div style="padding:10px;border:1px solid rgba(128,128,128,.42);border-radius:6px;text-align:center"><div style="font-size:1.18em;font-weight:700">${esc(reaction.name)} (${esc(reaction.en)})</div><div style="opacity:.76">${esc(reaction.range)}</div></div><details style="margin-top:9px"><summary style="cursor:pointer;font-weight:700">Описание</summary><div style="margin-top:8px">${row("Общая реакция",reaction.general)}${row("В потенциально боевой ситуации",reaction.combat)}${row("Коммерческие сделки",reaction.business)}${row("Просьбы о помощи",reaction.help)}${row("Просьбы об информации",reaction.information)}${row("Лояльность",reaction.loyalty)}</div></details></div>`});
}
